# Generated by Django 4.2.1 on 2023-06-06 22:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0001_initial'),
        ('chat', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='all_user',
        ),
        migrations.RemoveField(
            model_name='room',
            name='freelancer',
        ),
        migrations.AddField(
            model_name='room',
            name='first_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='first_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='room',
            name='second_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='second_user', to='user.freelancer'),
        ),
    ]
